### ISSUE TITLE
functioning issues

### ISSUE THREAD

**Issue by dejadabber** [boppescripting/boppe-jobcreator#2]
i have it installed go into the server to use it the commands show up as i type them, as soon as i hit enter nothing happens, i dont know what the issue is.

**Comment by youngcroes** [comment]
Have the same issue, any help?

**Comment by boppescripting** [comment]
> Have the same issue, any help?

Most likely due to the permissions check on the server-side... there may have been an update to how they work since this script was created. Take a look there.

**Comment by youngcroes** [comment]
I check already, I add god, admin and mod at config.lua of the script, just like the server config.lua, when I use /createjob or /creategang, it doesn´t show nothing

**Comment by youngcroes** [comment]
Im using qbcore btw, I don´t know if there is something different I have to do

**Comment by boppescripting** [comment]
> Im using qbcore btw, I don´t know if there is something different I have to do

I would hope you're using QBCore as this script never supported anything else.

Take a look at the QB documentation on permissions, see how they do checks, and then update the code.

**Comment by sabotage93thctv** [comment]
same issue here

**Comment by sabotage93thctv** [comment]
even if i change it to god or admin as the server owner it wont show after entering the command

**Comment by sabotage93thctv** [comment]
found a fix if you use admin menu and add yourself as god or admin it will then work
